import type { Locale } from "@/i18n/locales";

export const FILTER_KEYS = ["all", "ending-soon", "hackathon", "grant", "api-credits", "online", "prize"] as const;
export type FilterKey = (typeof FILTER_KEYS)[number];

export const HERO_CHIP_KEYS = ["all", "ending-soon", "new", "online", "prize", "api-credits"] as const;
export type HeroChipKey = (typeof HERO_CHIP_KEYS)[number];

export const copy = {
  en: {
    siteName: "AI Opportunity Atlas",
    nav: ["Discover", "Categories"],
    title: "Find AI opportunities before they close.",
    intro: "Curated hackathons, credits, grants, and events from trusted sources.",
    search: "Search hackathons, credits, grants...",
    searchLong: "Search opportunities, e.g. hackathons, grants, API credits...",
    searchCategories: "Search categories or opportunities...",
    chips: ["All", "Ending soon", "New", "Online", "Prize", "API credits"],
    filters: {
      all: "All",
      "ending-soon": "Ending soon",
      hackathon: "Hackathons",
      grant: "Grants",
      "api-credits": "API credits",
      online: "Online",
      prize: "Prize",
    },
    closing: "Closing Soon",
    closingSmall: "Deadline Watch",
    closingSub: "Opportunities closing soon",
    all: "All opportunities",
    more: "View more opportunities",
    endingMore: "View all ending soon",
    recommended: "Recommended",
    results: "results",
    save: "Save",
    scoreIndex: "Recommendation",
    details: "Details",
    online: "Online",
    global: "Global",
    filtersButton: "Filters",
    categoriesTitle: "Browse by what you need next",
    categoriesIntro: "Choose a path, then refine by deadline, format, and reward.",
    smartFilters: "Smart filters",
    reset: "Reset",
    filterNames: ["Deadline", "Format", "Reward", "Region", "Skill level"],
    any: ["Any time", "Any format", "Any reward", "Any region", "Any level"],
    explore: "Explore path",
    nextDeadline: "Next deadline:",
    categoryResults: "Matching opportunities",
    categoryResultsSub: "Filtered by your path and smart filters",
    clearSelection: "Clear selection",
    selectPathHint: "Select a path below to see matching opportunities",
    longTerm: "Long-term",
    verified: "verified",
    dataUpdated: "Data updated {age}",
    dataStale: "May be outdated",
    noResults: "No matching opportunities",
    detail: {
      discovery: "Discovery",
      officialEntry: "Official entry",
      enterOfficial: "Enter official page",
      deadline: "Deadline",
      region: "Region",
      difficulty: "Difficulty",
      difficultyUnset: "Not rated",
      reward: "Reward",
      participation: "Participation",
      winningCriteria: "Winning criteria",
      timeline: "Timeline",
      source: "Source",
      discovered: "Discovered",
      maintainedRecord: "Maintained record",
    },
  },
  zh: {
    siteName: "AI 活动雷达",
    nav: ["发现", "分类"],
    title: "在时间截止前找到 AI 机会",
    intro: "精选黑客松、积分、资助、挑战和活动机会",
    search: "搜索黑客松、积分、资助...",
    searchLong: "搜索机会，例如黑客松、资助、API 积分...",
    searchCategories: "搜索分类或机会...",
    chips: ["全部", "即将截止", "最新", "线上", "奖金", "API 积分"],
    filters: {
      all: "全部",
      "ending-soon": "即将截止",
      hackathon: "黑客松",
      grant: "资助",
      "api-credits": "API 积分",
      online: "线上",
      prize: "奖金",
    },
    closing: "即将截止",
    closingSmall: "Deadline Watch",
    closingSub: "近期截止机会",
    all: "全部机会",
    more: "查看更多机会",
    endingMore: "查看全部即将截止",
    recommended: "推荐排序",
    results: "条结果",
    save: "收藏",
    scoreIndex: "推荐指数",
    details: "详情",
    online: "线上",
    global: "全球",
    filtersButton: "筛选",
    categoriesTitle: "按下一步目标浏览",
    categoriesIntro: "选择路径，再按截止时间、参与形式和奖励继续筛选。",
    smartFilters: "智能筛选",
    reset: "重置",
    filterNames: ["截止时间", "形式", "奖励", "地区", "难度"],
    any: ["任意时间", "任意形式", "任意奖励", "任意地区", "任意难度"],
    explore: "查看路径",
    nextDeadline: "下一截止：",
    categoryResults: "匹配的机会",
    categoryResultsSub: "按所选路径与智能筛选显示",
    clearSelection: "清除选择",
    selectPathHint: "选择下方路径查看对应机会",
    longTerm: "长期开放",
    verified: "已验证",
    dataUpdated: "数据更新于 {age}",
    dataStale: "可能不是最新",
    noResults: "没有匹配的机会",
    detail: {
      discovery: "发现",
      officialEntry: "官方入口",
      enterOfficial: "进入官方页面",
      deadline: "截止时间",
      region: "地区",
      difficulty: "难度",
      difficultyUnset: "未标注",
      reward: "奖励",
      participation: "参与方式",
      winningCriteria: "获奖条件",
      timeline: "时间节点",
      source: "来源",
      discovered: "发现时间",
      maintainedRecord: "维护记录",
    },
  },
} as const satisfies Record<Locale, Record<string, unknown>>;
